# using basic template
# and https://github.com/eugeneyan/eugeneyan/blob/master/.github/workflows/build.yml
name: README Update

# Controls when the workflow will run
on:
  # trigger on push to any branch or manually
  workflow_dispatch:
  push:
  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repo
      uses: actions/checkout@v2      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
      # parser script has no dependencies
      # create requirements.txt and uncomment if that changes
      #- name: Install dependencies
      #run: python -m pip install -r requirements.txt

    - name: Setup git on container
      run: |-
        git config --global user.email "action@github.com"
        git config --global user.name "README-bot"

    - name: Update README
      run: |-
        python3 parser.py
